apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../charts/nginx  # Reference the Helm chart in the repo

namespace: default  # Can be changed in overlays
namePrefix: myprefix-  # Adds a prefix to all resources
