apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-namespace  # Override the namespace for dev environment

resources:
  - ../../base  # Reference the base Kustomization

namePrefix: dev-  # Prefix all resources for the dev environment
